### ISSUE TITLE
Roadmap to 1.16.5

### ISSUE THREAD

**Issue by pixelgamewizard** [pixelgamewizard/pgwbandedtorches#3]
- [x] Update source code
- [x] Update textures to be consistent with 1.16.5
- [x] Create a mod icon
- [x] Update documentation
- [x] (Optional) Add banded soul torches
